name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
          rustup toolchain install nightly --profile minimal
          rustup default nightly
          rustup component add rustfmt
      - name: Test
        run: cargo test

  format:
    name: Format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
          rustup toolchain install nightly --profile minimal
          rustup default nightly
          rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all --check

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
          rustup toolchain install nightly --profile minimal
          rustup default nightly
          rustup component add clippy
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -Dwarnings
